### PR TITLE
Support Auto-Discovery / Fix missing lib for testing / Upgrade phpunit / Make it compatible with PHP 7.2

### PR DESCRIPTION
**Pull request by stephane-monnot**
* Support Auto-Discovery
 * Fix missing lib for testing
 * Upgrade phpunit
 * Make it compatible with PHP 7.2 (related to #29)
 * Remove php 5.6 7.0 compatibility

We have to remove PHP 5.6, 7.0 compatibility because laravel 5.6 and phpunit 7 require php ^7.1.3 .
Maybe create a branch before merging this PR to keep a old support branch for old version. 
@hootlex What do you think about it ?

### CODE REVIEW

**Comment by hootlex** [comment]
Thank you Stephane ❤️

Would it be possible to keep php 5.6 support and only update the dev-dependencies for testing on Travis?

If we are about to drop support for php 5.6 this should be a major version so it doesn't affect users that are still using it.

**Comment by stephane-monnot** [comment]
You're welcome :) 
It's possible to keep php 5.6 support, but we can't test it with Travis, because the class TestCase of Laravel uses Phpunit 7 and Laravel itself uses PHP7.1.
Do you want me to revert this change : 
```php
"require": {
-    "php": ">=5.4.0"
+    "php": "^7.1.3"
},
```

**Comment by hootlex** [comment]
@stephane-monnot Thanks for explaining. I think it's acceptable to not test it in Travis but keep support for php 5.6 until the package is not compatible any more.

**Comment by stephane-monnot** [comment]
Done

**Comment by hootlex** [comment]
@stephane-monnot thank you!

**Pull request merged**
