### PR TITLE
Added Postpone Status and also moderated_by column

### PR DESCRIPTION
**Pull request by drtzack**
Sometimes I may need to postpone some records or the record has to be review by another guy so I need one more status which is postpone. 

Also I need to see who approved the record which admin or mod.

### CODE REVIEW

**Comment by drtzack** [comment]
Added tests for PR

**Comment by hootlex** [comment]
Hey @drtzack, 

I see that moderated_by column is required in order to use the package. 

This means that anyone who gets the update will be forced to migrate the database again or his app will be broken. (that's why the tests failed in your second commit)

I suggest to make moderated_by column `NULL` by default inside config, and use 'moderated by' feature only if moderated_by (config) or `static::MODERATED_BY` (model) is set.

Please revert tests to the previous state and create a new one to test your pr. 

Thanks for your contribution.

**Comment by drtzack** [comment]
I did everything except making new test.

**Comment by hootlex** [comment]
I created the tests myself. You had some serious bugs like https://github.com/hootlex/laravel-moderation/commit/4d061918fd66adc5c285096a2ad87d9a7edb022a or https://github.com/hootlex/laravel-moderation/commit/baba393ee6169bae61eef7b9b66078c90999794c.

**Comment by drtzack** [comment]
Thank you.

**Pull request merged**
