### PR TITLE
Improve the travis build

### PR DESCRIPTION
**Pull request by stephane-monnot**

### CODE REVIEW

**Comment by stephane-monnot** [comment]
@hootlex Check and if ok, can be merged

**Comment by hootlex** [comment]
@stephane-monnot thanks! I will also integrate code-climate when I have some time.

**Comment by stephane-monnot** [comment]
@hootlex I wanted to suggest you integrate code-climate, but I knew you will do :wink: .

**Comment by hootlex** [comment]
@stephane-monnot yeah, it's too cool! If you use it once, you have to use it everywhere.

**Comment by stephane-monnot** [comment]
I disable xdebug in the travis file, if don't know how the code climate extension get the code coverage. So if you can't get, try to delete the xdebug disable line in the travis. If you don't need to remove this line, we can optimize the travis build of laravel friendship package by removing the xdebug extension ;).

**Comment by hootlex** [comment]
I think it's mandatory to have xdebug enabled for codeclimate to work. So, I will enable it when time comes.
Thanks for pointing it out.

**Pull request merged**
