### PR TITLE
Fix composer error on build and add L5.3 compatibility

### PR DESCRIPTION
**Pull request by stephane-monnot**
Problem: composer.lock cached in vendor/laravel/laravel

### CODE REVIEW

**Comment by stephane-monnot** [comment]
@hootlex could we remove hhvm build ? the constant "ARRAY_FILTER_USE_BOTH" is not available in the hhvm 3.3. It is used by laravel 5.3. Maybe replace with php7 ?

**Comment by hootlex** [comment]
@stephane-monnot sounds good to me

**Comment by stephane-monnot** [comment]
@hootlex I applied #14 changes. (remove hhvm and add php7)

**Comment by hootlex** [comment]
@stephane-monnot @lukasoppermann thanks guys!

**Pull request merged**
